"""create_model

Revision ID: 6e58c12f147c
Revises: 
Create Date: 2023-11-10 00:53:39.480575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e58c12f147c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Uuid(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('fk_medicine_id', sa.Integer(), nullable=False),
    sa.Column('fk_user_id', sa.Uuid(), nullable=False),
    sa.Column('how_to_take', sa.Enum('NOTSTATED', 'AFTERMEAL', 'BEFOREMEAL', 'BETWEENMEALS', 'DURINGMEAL', 'BEFOREBED', 'EMPTYSTOMACH', 'EVERY', name='timeofmedicine'), nullable=False),
    sa.Column('npills', sa.Integer(), nullable=False),
    sa.Column('ndays', sa.Integer(), nullable=False),
    sa.Column('sttm', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ettm', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fk_medicine_id'], ['medicine.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fk_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe')
    op.drop_table('user')
    op.drop_table('medicine')
    # ### end Alembic commands ###
